ChainID = '69'
ChainType = 'optimism'
FinalityDepth = 200
LinkContractAddress = '0x4911b761993b9c8c0d14Ba2d86902AF6B0074F5B'

NoNewHeadsThreshold = '60s'
TxResendAfterThreshold = '30s'

[GasEstimator]
EIP1559DynamicFees = true

[GasEstimator.BlockHistory]
BlockHistorySize = 24

[HeadTracker]
HistoryDepth = 300
