ChainID = '10'
ChainType = 'optimism'
FinalityDepth = 200
LinkContractAddress = '0x350a791Bfc2C21F9Ed5d10980Dad2e2638ffa7f6'

NoNewHeadsThreshold = '60s'
TxResendAfterThreshold = '30s'

[GasEstimator]
EIP1559DynamicFees = true

[GasEstimator.BlockHistory]
BlockHistorySize = 24

[HeadTracker]
HistoryDepth = 300
