name: Integration Soak Test
on:
  # pull_request:
  schedule:
    - cron: '0 */3 * * *'
  # workflow_dispatch:
  #   inputs:
  #     cl_branch_ref:
  #       description: Chainlink repo branch to integrate with
  #       required: true
  #       default: develop
  #       type: string
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.src }}
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'integration-tests/**/*'
              - 'core/services/vrf/**/*'
              - '**/*go.sum'
              - '**/*go.mod'
  build-chainlink:
    environment: integration
    name: Build Chainlink Image
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build Image
        uses: smartcontractkit/chainlink-github-actions/chainlink-testing-framework/build-image@010068ddc7dd55cd4439159a485390aa651fdd39 # v2.0.3
        with:
          cl_repo: smartcontractkit/chainlink
          cl_ref: ${{ github.sha }}
          push_tag: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink:latest.${{ github.sha }}
          QA_AWS_REGION: ${{ secrets.QA_AWS_REGION }}
          QA_AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
  soak:
    environment: integration
    name: VRFV2 Soak Tests
    permissions:
      checks: write
      pull-requests: write
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    needs: [changes, build-chainlink]
    if: ${{ needs.changes.outputs.src == 'true' }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Run Tests
        uses: smartcontractkit/chainlink-github-actions/chainlink-testing-framework/run-tests@v010068ddc7dd55cd4439159a485390aa651fdd39 # v2.0.3
        with:
          test_command_to_run: SOAK_NAMESPACE=ci make test_soak_vrfv2 args="-nodes=10"
          test_download_vendor_packages_command: make gomod
          test_download_ginkgo_command: make test_install_ginkgo
          cl_repo: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink
          cl_image_tag: latest.${{ github.sha }}
          artifacts_location: ./integration-tests/smoke/logs
          token: ${{ secrets.GITHUB_TOKEN }}
          publish_check_name: Vrfv2 Soak Test Results
          QA_AWS_REGION: ${{ secrets.QA_AWS_REGION }}
          QA_AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
          QA_KUBECONFIG: ${{ secrets.QA_KUBECONFIG }}
          
